### ISSUE TITLE
Search Functionality Prototyping

### ISSUE THREAD

**Issue by francisrupert** [USDA-FSA/fsa-design-system#103]
### Task

Identify, design, build, and deploy a **basic**, MVP-ish solution to search.
### Challenge

While there are many Jekyll plugins available for this, gh-pages disabled plugins. 
### Current thinking

Speculative approach...
1. Precompile a `/index.json` file that effectively indexes contents of each `.yml` config or date file.
2. Find a way to parse search submissions against that `json` file
3. Populate a Mustache template to `/search-results` or some such.

There's gotta be something like this done so I don't have to script that out, particularly relative to priority and nice-to-have-ishness of this feature.

**Comment by francisrupert** [comment]
Inspiration: 
- https://github.com/christian-fei/Simple-Jekyll-Search
- http://fusejs.io/
- https://github.com/slashdotdash/jekyll-lunr-js-search
  - http://10consulting.com/2013/03/06/jekyll-and-lunr-js-static-websites-with-powerful-full-text-search-using-javascript/
  - https://gist.github.com/flohei/91d987a1827023bef8ca

**Comment by francisrupert** [comment]
@bignamehere,

I'd love to get your take on how _some form_ of Search functionality can be had within our tech constraints -- particularly with `gh-pages` not playing nice with plugins. I don't have requirements to put on you beyond _"should generally not be complex"_.

I suspect the UI would be dictated by the possible tech solutions we discover, so limit this purely to  exploring the tech side of things and we'll cross the UI bridge when we need to.

Research possible solutions, prototype them out, propose a solution, etc. Even if your eventual output isn't necessarily full-on working implementation, some sort of documented report of your findings and recommendations would be extremely useful.

**Comment by bignamehere** [comment]
@francisrupert I have started working on a prototype that basically pulls the HTML content from the sitemap/index.html page, and creates an array of objects based on anchor tags with class of `ds-sitemap__link`. This gave me 74 phrases with links to the individual pages for each of those phrases. We can make the dataset more advanced if we added a short description to something related to those links. The good thing is that it will be automated based on how the sitemap is currently built dynamically and based on the HTML content of the sitemap, which should have all links to every page on it.

Since the results page would be maybe one or two results max, we might forgo taking someone to one, and use an on-screen display of results. I imagine a Smart Search would be a nice feature, where a Person started typing a topic, like Color, then below the Input a dropdown would fill with with matching strings and link to the page as they type...

[_ Col _________] SEARCH BUTTON
- Color - /visual-style/color
- Color and Contrast - /guides/accessibility/color-and-contrast

then the User can just click on the dropdown.  This functionality would need to be build though, as it doesn't exist within our components.

thoughts?

**Comment by bignamehere** [comment]
@francisrupert pull down feature branch 103, and take a look. We can make it more robust in a number of ways, and you can make it pretty, but it's a good start. It uses all vanilla JS, as well.

thoughts?

**Comment by francisrupert** [comment]
@bignamehere,

This is a great start! _Autocomplete_ as the UI pattern is probably the most relevant for this site. You've got the right idea in keeping it simple, and I agree we shouldn't create additional overhead as the site updates. 

As far as the script goes, it looks like you've effectively recreated [Simple-Jekyll-Search](https://github.com/christian-fei/Simple-Jekyll-Search) ([demo](https://christian-fei.github.io/Simple-Jekyll-Search/)) that I listed as a comment before. 

That one [parses a `json` file](https://christian-fei.github.io/Simple-Jekyll-Search/search.json) built via Liquid from the `yml` files, while yours parses through HTML also built via Liquid from the `yml` files. I'd say the `json` approach is the most pure. 

Since the parsed source comes from the `yml` files via Liquid, feel free to propose other useful attributes originating in the `yml` file. For example, searching for "Drop Down" can return "Select", or "Segment" returns "Button Group." 

I'd like to see the UI reflect hierarchy, probably doable given the nested structure of the parsed source. In addition to just being a nice labeled structure, it can help train users how to _categorize_ things.

User enters _"Form"_

 COMPONENTS
 **Form** Elements                                                  
 **Form** Elements / **Form** Field

 GUIDES
 Accessibility / **Form**s
 Applications / Date **Form**at
 Applications / **Form**s
 Applications / **Form** Validation

I'm not too married to the idea of _fuzzy_ searching, but that is one thing that looked compelling about https://fusejs.io/

**Comment by francisrupert** [comment]
Side note: since I [published `1.14.2` this morning](https://github.com/orgs/USDA-FSA/projects/12#card-32389942), this issue is now part of 
[`Design System: 2.5.0 / 1.15.0`](https://github.com/orgs/USDA-FSA/projects/14#card-36370100)

**Comment by bignamehere** [comment]
@francisrupert One of the things that occurred to me as I was reviewing the Jekyll example, was while it is a fairly simple approach, there is certainly no need to be dependent on any type of plugin for basic Quick Search functionality. Here are the pros and cons of the Jekyll Search:

Pros:

- Fairly easy to implement
- Using Jekyll and yml that is currently in use
- Provides a very simplistic approach to a Quick Search feature
- It uses Liquid to automatically generate JSON for parsing

Cons:

- It has strict dependancies on Jekyll. Liquid, and yml
- If you switch from Jekyll to another templating engine you must strip out the features and functionality
- If you move to a Webpack implementation, you should use Vue or some other SPA to run the Design System in a more modern way.
- Because it using Liquid to automatically generate the JSON, you must alway implement this feature/functionality on anything you want to "index" 
- There are unknowns about how the code works, and we are unable to tweak it to how we want.

After thinking about it a while, it made much more sense to build a Vanilla Javascript example, that parses an HTML page. 

Pros:

- Works in any implementation that uses JavaScript and HTML
- No dependancies on any plugins, we own the code and feature set
- Can work with any HTML page on the site (or even on the same domain)
- No need to have a plugin like Liquid to create JSON, just point to final exported HTML page
- More Flexibility to fine tune the search to any CSS Class, ID, etc.
- In theory, you can point the `url` at any page on the domain or with [CORS Anywhere](https://cors-anywhere.herokuapp.com/) any publicly available link on the web and use the content.
- It is very simple JavaScript to understand or update.
- HTML is just as universal and searchable as JSON
- Can be augmented with a JSON document for additional search criteria, including Liquid to JSON automatic exports.

Cons:

- Requires knowledge of JavaScript to update
- Might require the CORS Anywhere library if you want to create a search that can pull content from other websites.
- ??

As a proof of concept, I  updated the below two lines of code, and the search worked perfectly:

//url: 'http://usda-fsa.github.io/fsa-design-system/sitemap/',
url: 'https://logaretm.github.io/vee-validate/overview.html#getting-started',

//let list = [].slice.call(holder.querySelectorAll(".ds-sitemap__link"))
let list = [].slice.call(holder.querySelectorAll(".sidebar-link"))

From localhost, you wouldn't see any CORS issues, but again, you can use CORS Anywhere if we really wanted to expand on the capabilities of this search feature. We also might be able to pull in content from the Kitchen sink example on FSA-Style, as well. We need to get this up on GitHub.io to test out what CORS issues come at us. In a perfect world, since everything is on Github.io, we could search any site hosted on that domain without any issues.

I am still exploring the fusejs.io, and can see how it might be really powerful. But ultimately, the data source is the real challenge here, not really the logic engine to parse the data.

**Comment by bignamehere** [comment]
Updated the prototype to be able to include on any page of the Design System. Just add `custom_js: "ds-quick-search.js"` to the top of the page controls, and then add the below: 

```
<input class="fsa-input" size="35" id="quick-search-id" type="text" name="search" value="" placeholder="Quick Search">
<div id="quick-search-results-id"></div>
```

The prototype now searches the sitemap page of the Design System, and the Kitchen Sink page (top nav) and includes those pages in the result.

**Comment by bignamehere** [comment]
@francisrupert I know you had some initial comments above about hierarchical display of data, but before we go down that route, what are your thoughts on how this component should look? More specifically, the `<div id="quick-search-results-id"></div>` container that gets dynamically built.

Here are some examples and considerations that I have looked at:

https://docs.adobe.com/content/help/en/experience-manager-core-components/using/components/quick-search.html

https://semantic-ui.com/modules/search.html

https://developer.salesforce.com/blogs/2018/07/10-tips-for-implementing-an-efficient-lightning-lookup-component.html

https://baymard.com/blog/autocomplete-design

what are your thoughts?

**Comment by bignamehere** [comment]
@francisrupert One of the things I didn't like about how this feature was being implemented, was the use of CSS within JavaScript. If at all possible, using CSS classes to control the functionality of JavaScript should be avoided, because this tightly couples the functionality of a feature, with the style of the page/elements. Changing a Class would becomes a breaking change within the JavaScript. 

With that in mind, I've been exploring other means to allow JavaScript to identify page elements by non-CSS properties or attributes and categorize them. I landed on data=* attributes and was headed down that path while building out the prototype to include hierarchal display of the phrase being search. I thought I landed on a solution, but after many attempts, it seems I found a major blocker.

The current solution utilizes the HTML that is pulled back via XHR and parses all sorts of things, but for some reason I wasn't able to get the below to give me all of the anchor elements on the page and add them to a collection.

```javascript
 holder.querySelectorAll( `[data-search-type]` )
``` 

I finally figured out why I was able to do a `querySelectorAll( ... )` for any and all CSS, but not for any data-* attributes. It is because the text string being parsed from the XHR, did not include any of the data-* attributes, even though they appeared in the sitemap.html page when doing a View Source as seen here:

![Screen Shot 2020-05-11 at 1 21 38 PM](https://user-images.githubusercontent.com/2124049/81596841-5b9ce400-938a-11ea-90d3-4c3399d2012e.png)

I believe because we are only adding the HTML string to a holder, using `holder.innerHTML` as seen in below screenshot, and NOT adding the holder to the DOM, the data-* attributes for some reason are not within the HTML string of the XHR response. 
 
![Screen Shot 2020-05-11 at 1 23 52 PM](https://user-images.githubusercontent.com/2124049/81597043-aa4a7e00-938a-11ea-90c6-6f75929c850a.png)

I was implementing the hierarchy based on the ability to have `data-search-type` provide me with root, group, title, subgroup, or subtitle as a value, but it looks like this might be a dead end, because it seems a rendered DOM might be required to "inject" these data-* attributes into the HTML when the page is loaded. Looking at the dataset object within Dev Tools shows an empty `DOMStringMap`, which leads me to believe my above hypothesis.

<img width="209" alt="Screen Shot 2020-05-11 at 1 34 24 PM" src="https://user-images.githubusercontent.com/2124049/81597954-22fe0a00-938c-11ea-96c6-21e2cea263a0.png">


At the very least, hitting a dead end in a long and winding alley was educational, but it seems we might need to break the rules a bit, **so I need your opinion on how to proceed.**

Would you prefer to utilize the ID attribute of an anchor tag or a CSS class specific only to the search feature? CSS class is the easiest, but I would lean towards the ID, because it shouldn't generally be used for CSS, but I want to make sure we are not using ID on other anchors within the Design System for the purpose of styling a page.

Instead of using the data-* attribute, in the previous way, I planned on exploring the concept of appending a unique GUID to an ID to all links on the sitemap, like this:

```
<a id="search-root-GUID" href=" .....
```

Let me know your thoughts on this as I continue to explore a solution that can be scalable to more than just the sitemap as well.

**Comment by francisrupert** [comment]
@bignamehere,

I started a preliminary stab on what Quick Find's UI might be, but noticed certain keywords weren't returning expected results. I first noticed it with typing a string of "Button" expecting [Components > Buttons](http://usda-fsa.github.io/fsa-design-system/components/buttons/index.html) as a result -- same for _all_ Components.

I then noticed `class="ds-sitemap__link"` wasn't on all Sitemap link items. Even after adding it to the Liquid on `\fsa-design-system\sitemap\index.md` it still wasn't returning it. 

I'm assuming it's because `ds-quick-search.js` anticipates a specific DOM structure and that piece doesn't conform since they are grouped on further nested level on the Sitemap tree.

Meanwhile, merge in my branch `feature/103_UI` to your `feature/103` working branch to see what I've done to replicate what I've described above.

**Comment by francisrupert** [comment]
@bignamehere,

Pull down `feature/103_UI` to view my proposed HTML/CSS for Quick Find. Screenshots seen below. 

In particular pay close attention to detail on the `aria` attributes in play. Note that keyboard support will be necessary for full compliance (e.g. up/down arrows for results, toggle `aria-selected` attribute value, etc).

Let me know if you've any questions. 

| Default  | Entry |
|---|---|
| ![quick-find--empty](https://user-images.githubusercontent.com/1165933/81737020-14cbee80-945d-11ea-96f4-6465c4b24c6e.png)  | ![quick-find](https://user-images.githubusercontent.com/1165933/81737028-17c6df00-945d-11ea-9154-324c3fb5e39a.png)  |

**Comment by francisrupert** [comment]
@bignamehere,

Interesting that the `data` attributes are stripped. Unfortunate.

> ...Would you prefer to utilize the ID attribute of an anchor tag or a CSS class specific only to the search feature? CSS class is the easiest, but I would lean towards the ID, because it shouldn't generally be used for CSS, but I want to make sure we are not using ID on other anchors within the Design System for the purpose of styling a page.

I definitely always use `data` attributes over attaching to CSS selectors, most especially seen from our prototyped `data-behavior` attributes.

It seems using `id` attributes that are autogenerated (presumably via Liquid) is a bit overkill. I'm not all that averse to using a CSS selector for this specific purpose, as long as the naming convention is obviously not for style. I suppose that could be like...

```
js-quick-find--root
js-quick-find--subgroup
js-quick-find--foo
js-quick-find--bar
```

Yes, not ideal, but actually quite commonly done and could appropriately solve this `data` attributes being stripped; and a whole lot simpler to dev and maintain.

**Comment by francisrupert** [comment]
@bignamehere,

Since the Sitemap did not include all **Getting Started** and (more importantly) the **Utilities** pieces (i.e. the Jump Menu), I added them to `navvy.yml` so they may be findable via this "Quick Find" functionality. Granted, this isn't most elegant solution since those items (e.g. "Margins") would have to be maintained in two different places; I'm fine with this for now.

It's on one of my working branches I haven't merged yet, but you can probably **cherry-pick it off commit: ace270e**.

Below is a screenshot of what that sitemap tree looks like now:

![localhost_4000_fsa-design-system_sitemap_ (1)](https://user-images.githubusercontent.com/1165933/81851151-a18ab100-951e-11ea-8223-e8c1a103b7b1.png)

**Comment by bignamehere** [comment]
@francisrupert pull done the latest, because I think I have it working mostly as planned. It looks like it still needs...

- Clicking on X triggers `searchInput` to clear results
- Aria considerations... what needs to be added?

**Comment by francisrupert** [comment]
@bignamehere,

That is smooth. I haven't looked into how you achieved it, but I'm sure it was a bear based on our conversation yesterday. 

I'll continue to stress-test it a bit more, along with providing an outline of additional UI requirements for a11y considerations and all. 

Great progress!

**Comment by francisrupert** [comment]
@bignamehere,

I'm breaking out additional activity on this Quick Find feature to a new issue, since the initial intent of this issue (exploration/feasibility/prototyping) has more than been met. I'll get that written up and assigned to you.

Great job!
