### ISSUE TITLE
Update Radio Button Examples

### ISSUE THREAD

**Issue by bignamehere** [USDA-FSA/fsa-design-system#178]
The Radio Button examples need to switch out the `<span>` for an `<ul>`.

![image](https://user-images.githubusercontent.com/2124049/39211524-80572da2-47d1-11e8-821b-5eddb6f8d760.png)

**Comment by francisrupert** [comment]
@bignamehere,

I assume you logged #178 and #179 since you were distracted by the `<span>` wrapping each item, as seen in the screenshot below. If that was the sole reason for those two issues, we can close them.

Wrapping with the `<span>` was intentional. While not required, and won't hurt anything if omitted, it's a safer play to contain them together.

## Background

The checkbox and radio component is the one I'm not happy with how I authored it. It's out of sync with the consistent naming approach of everything else. Instead of...

```html
<input class="fsa-checkbox"....>
<label....>
```

...I should have done...

```html
<span class="fsa-checkbox">
  <input class="fsa-checkbox__item"....>
  <label class="fsa-checkbox__label"....>
</span>
```

Far too late to do anything about it, so in the meantime I generally recommend containing them together with that `<span>`.

## Screenshot

![image](https://user-images.githubusercontent.com/1165933/41048761-14b20a84-6975-11e8-9e49-01292f855358.png)
