### ISSUE TITLE
Docs: Modal vs Growl vs Inline Alerts

### ISSUE THREAD

**Issue by francisrupert** [USDA-FSA/fsa-design-system#186]
## Redefining this Issue
The initial intent of this issue is archived below under "Initial Post." I'm redefining this issue as the following:

Edit docs for Modal, Growl, and Inline Alerts to further distinguish use/don't use.

## Initial Post
In meeting with CPAS for early-phase UX consulting, their BA was confused by this **Don't** on [Modal doc page](http://usda-fsa.github.io/fsa-design-system/components/modal/):

> Don’t Use when the content within the Modal requires the screen to scroll.

**Comment by bignamehere** [comment]
@francisrupert - Can you provide more context on what you believe we should instruct the User to do? There is a quite the online debate related to content in a modal that is scrollable, how it should be handled, and what is the optimal User Experience. I personally tend to lean more towards smaller modal windows with less content (no scrolling), because that much content should be a process that happens within the application itself. It is also a reason, I believe the fullscreen modal could be used inappropriately.

Thoughts?

**Comment by francisrupert** [comment]
(Side note: I've redefined this issue a bit. Refer to [edited initial post](https://github.com/USDA-FSA/fsa-design-system/issues/186#issue-336296734))

**Comment by francisrupert** [comment]
@bignamehere,
 
I've added/edited some doc language for Modal, Growl, and Inline Alerts to distinguish and relate them a bit more.
 
I'm closing this, but feel free to review the changes I made on 3199da2

**Comment by bignamehere** [comment]
@francisrupert I don't see anything that would require opening up the issue and updating.
