### ISSUE TITLE
Cookie Page Title Actions

### ISSUE THREAD

**Issue by francisrupert** [USDA-FSA/fsa-design-system#320]
### Background

Documentation views include Switches to toggle visibility of Code and the X-Ray. Feedback has been received that they'd like its state retained from page to page.

### Tasks

Maintain user's selections for...

- [x] Show Code
- [x] X-Ray

**Comment by bignamehere** [comment]
@francisrupert to clarify... is this to cookie for the site, or for the individual page? Meaning, should each page has an individual preference for the Action, or the entire site?

**Comment by francisrupert** [comment]
@bignamehere,

I'm thinking across the site. If I toggle the Show Code swtich to on on Buttons, it would be turned on across all pages with that Switch.

Have an opinion?

**Comment by bignamehere** [comment]
@francisrupert I feel like form a UX perspective, that seems the most appropriate.... a site-wide control.

**Comment by bignamehere** [comment]
@francisrupert this is mostly finished, and you can take a look at functionality. One thing that I am not a fan of is how the X-ray and Show Code JS files are basically identical, and it would be 100x better if we could just us a class here to create two instances of the same codebase. I will look into that next.

**Comment by francisrupert** [comment]
@bignamehere,

It's looking solid. I've stress-tested it across many pages, including validating across suite of browsers.

Agree on refactoring.

**Comment by bignamehere** [comment]
@francisrupert I was able to abstract the code into a "class" in order to use it for other page-based toggle functionality. 

Something to note for [347](https://github.com/USDA-FSA/fsa-design-system/issues/347). This toggle code is very specific to applying CSS to the Body and also storing the state of the toggle, so it can't be used as a global toggle that works for[ issue 347](https://github.com/USDA-FSA/fsa-design-system/issues/347). 347 seems to be more specific to a hide/show of an individual page element, which would probably be something that can also be abstracted to a class-like resource. I will close this issue, but if I see enough similarities in how the code works in 347 to this implementation, I will refactor all to use a singular class.

**Comment by francisrupert** [comment]
Awesome. I'm not currently able to test it out (new machine to setup, fun), but looking at the commits makes it clear to me what's going on. I see you've merged it over to `release/1.15.3`.
