### ISSUE TITLE
Icon Find

### ISSUE THREAD

**Issue by francisrupert** [USDA-FSA/fsa-design-system#413]
### Task

Much like the site's Quick Find feature, need an equivalent for Icons. Presumes careful planning and JS tasks.

### Assumed key challenge: 

Tapping into any MD available open source API to reuse their exhaustively-curated _keywords_ associated with with all 900+ icons. e.g. `house` finds `home`.

**Comment by francisrupert** [comment]
@bignamehere 

On the point of release branches: we’ll actually maintain the current name of `release/2.6.0` instead of renaming. 

**Reasoning:** While I will soon publish to https://www.npmjs.com/package/fsa-style as 2.6.0-RC1, I will _not_ be merging it to master nor will it be published to the Kitchen Sink page.

Once RC1 is published I will then create the `release/1.18.0` branch (read https://github.com/USDA-FSA/fsa-design-system/issues/404). 

That branch can be what you branch off on R&D for Icon Findability. Much like I did for Quick Find, I’ll probably stub out a basic UI on https://usda-fsa.github.io/fsa-design-system/components/icons/, and we'll enhance from there.

**Comment by francisrupert** [comment]
@bignamehere,

I've instantiated branch `release/1.18.0`, updated `package.json` with `fsa-style@2.6.0-RC1`, and stubbed out the Icons doc page with an initial UI for Icon Find (screenshot below). 

You should absolutely feel free to adjust that markup as appropriate (e.g. `data` attributes; change each `<a class="docs__icons__link">` to `<button class="docs__icons__link fsa-btn fsa-btn--plain">`, etc)".

I suspect the narrowing down scripting is relatively straightforward, while the metadata approach will be the biggest challenge (e.g. "house" or "home" finds `ic_home_24px`)

![image](https://user-images.githubusercontent.com/1165933/120514435-e6d08980-c392-11eb-96ec-9fc797b2fb3e.png)

**Comment by bignamehere** [comment]
@francisrupert pull this branch down and test out features and functionality. Let me know if you see anything not working as expected. Also, should we keep the link titles with metadata or get rid of it? While the metadata could add context as to why that icon was shown, the link titles are a bit long and kinda ugly. Thoughts?

Also, I will add the Icons Categories Filter as a separate Issue.

Lastly, what in your opinion should be be considering for ARIA?

**Comment by francisrupert** [comment]
@bignamehere,

Outstanding progress! Branch pulled down, `npm install`'d, and built smoothly. Functionality tested and confirmed working as expected. Definitiely move forward with #448. 

I'll follow-up later addressing your questions, possibly work a branch with some potential reactions -- including the loading state.

**Comment by francisrupert** [comment]
@bignamehere,

### Icon Pre-loading UI

Loading | Painted
------------ | -------------
![image](https://user-images.githubusercontent.com/1165933/124650413-54bf1380-de5f-11eb-8825-7873b4b1f09b.png) | ![image](https://user-images.githubusercontent.com/1165933/124650870-d7e06980-de5f-11eb-9416-757df7c77875.png)

Pull down my branch `issue/413-shimmer` for my proposed replacement of _"Loading, please wait"_ text. View it at http://localhost:4000/fsa-design-system/components/icons/index-static-html.html

This implements the **shimmer**/skeleton/wireframe effect. 

### Implementing

Upon load...

1. Remove the visually hidden (via `.fsa-sr-only`) "Loading icons..." `<div>`
1. Remove `aria-hidden="true"` from...
   1. "Previewing..." containing block
   2. Search field's containing block (`.fsa-field`)
   3. From `#ds-icon-find-results-id`
1. Remove each `<span class="docs__shimmer">...</a>`. Actually _remove_ the element wrapper, not just the class and value.
1. Remove `docs__icons--loading` from `#ds-icon-find-results-id`
1. Paint results of `#ds-icon-find-results-id`

Let me know if you've any questions or reactions to this UI.

**Comment by bignamehere** [comment]
I had to Google "Shimmer" to even know what I was looking into, because generally I have referred to this UX pattern as a Skeleton Screen or just Skeleton.

Here are my initial reactions...

1. It introduces a pattern, not currently documented or available within the Design System
2. Why aren't we using the existing and heavily documented [Progress component](https://usda-fsa.github.io/fsa-design-system/components/progress/)?
3. The overall philosophy of the Design System is to use the DS to build products, introducing patterns outside of the scope of the Design System goes against this philosophy. Why aren't we eating out own dog food?
4. By introducing yet another way to indicate Progress or Loading, it adds confusion for Development teams as to which pattern should be used and when. The Progress component currently serves as a loading indicator in various program applications, so why isn't this pattern/component being used?
5.  The visual affect that indicates "progress" is very hard to notice, even for a someone with no visual impairment. It seems like a 508 issue if a system is trying to communicate something with such a subtle indicator. The "Shimmer" is not noticeable. 
6. A User must have pre-existing knowledge of the Skeleton Pattern to know that the page isn't broken.
7. There is no Text-based indication ("Loading...") or message used within the pattern to help provide context... A text-based message could help solve the issues 5 and 6 above.
8. If this pattern were to be added to the Design System, what systematic approach could we use to ensure the pattern is implemented correctly?
9. We definitely wouldn't want to have Dev Teams come up with the Skeletons themselves (the anatomy of the Skeleton), so a CSS approach to the normal screen elements would be required, but with the nature of dynamically content, the page elements/layout/data will always be unknown until it has loaded.

Lastly, how is this new Skeleton approach better than the current implementation? How is this measured?

**Comment by bignamehere** [comment]
Closing this issue and opening another for the above Skeleton pattern consideration.

Merged into 1.18.0

**Comment by francisrupert** [comment]
A few minor UI tweaks added to Icon Find via commit 1adf1528b285a65e3ea4f30218caf9a5657deeff on branch `release/1.18.0`

* Refactored CSS a bit in `_sass\other\_ds.shame.scss`, to be moved to `fsa-style` once complete; https://github.com/USDA-FSA/fsa-style/issues/490
* Reformatted success state and message
