### ISSUE TITLE
Test and Validate Date Leap Year fix

### ISSUE THREAD

**Issue by francisrupert** [USDA-FSA/fsa-design-system#450]
`2.6.0-RC2` has been installed on `release/1.18.0` branch (via https://github.com/USDA-FSA/fsa-design-system/issues/449)

Confirm fix (https://github.com/USDA-FSA/fsa-style/issues/467) is good on doc site.

**Comment by francisrupert** [comment]
@bignamehere,

Any particularly unique testing that needs to be done for this? I've at least done a cursory confirmation of it with `2.6.0` in `release/1.18.0`.

**Comment by bignamehere** [comment]
@francisrupert I tested it in Chrome, Firefox, and Edge browsers. Unfortunately, we can’t test every possible valid AND invalid date, even with robust Unit Testing. I am confident in the very small change though, because the string manipulation still works exactly the same for YY date format, but also accounts for this bug of YYYY format as well.

I’m not too sure how to test any more thoroughly without Unit Testing.

**Comment by francisrupert** [comment]
Agree and understood.
