### ISSUE TITLE
Research and Recommend Tracking / Analytics Strategy

### ISSUE THREAD

**Issue by francisrupert** [USDA-FSA/fsa-design-system#69]
Google Analytics presumably, or [digitalgov.gov's DAP](https://www.digitalgov.gov/services/dap/)

**Comment by francisrupert** [comment]
@brianmillsUX,

I understand you've had quite a bit of experience with Google Analytics.  I say we make sure we get Tracking established in preparation for any public release.

Can you outline as a comment on this Issue what needs to be done: from an Administrative angle, from an FSA angle, establishing an opinion on why we would do so, and anything else you feel necessary. 

For that matter, should we be considering https://www.digitalgov.gov/services/dap/ (https://analytics.usa.gov/)?

I'll naturally take on the technical part, especially making sure it plays nicely with how Jekyll builds the static site. I already have a good handle on that, i.e. https://desiredpersona.com/google-analytics-jekyll/

**Comment by brianmillsUX** [comment]
Completely agree! For Google Analytics, the question is account protocol. At a high-level, we have to:
1. Leverage an existing account (research/time) or set-up a new, dedicated account (faster and easier).
2. Create four dedicated tags, to start (one for Design System plus one for each of the initial guides).
3. Include code for two distinct tags on all but the intro page (once you validate code, I can replicate).

While the process is more manual than technical, it will deliver greater benefit the sooner we do it. :)

**Comment by francisrupert** [comment]
Moving to Icebox.

**Comment by bignamehere** [comment]
@francisrupert 

This one seems to be pretty easy, as long as we want to utilize Google Analytics for tracking. One issue that needs to be accounted for in a long-term solution is the use of 3rd Party Cookies. With Google Chrome abandoning the use of 3rd party cookies within a 2 year period, it is critical that any tracking solution implemented should not include this technology solution (User Agent String) as a means to track Users.

Since GA is the most widely used tracking system, and does not use 3rd Party Cookies, it seems to be the most reliable and future-friendly solution.

Once a GA account is setup, it looks like it would take 10 minutes of updates in our current Jekyll system... [Reference One](https://www.christopherlovell.co.uk/blog/2015/04/13/google-analytics-ghpages.html) [Reference Two](https://desiredpersona.com/google-analytics-jekyll/)

Other alternative solutions include [Clicky](https://clicky.com/) and [Gauges](https://get.gaug.es/). While Clicky provides heat maps as a feature that might be interesting, there is a cost ($9.99/mo) associated with using the tool. Gauges is a free tool that seems to simplify User tracking, but further investigation is needed in order to determine if 3rd party cookies are being used, and it might also have little support. At first glance it looks like the technology portion of the API includes the User Agent string data.

Lastly, there is the GitHub Traffic tab that provides very basic states. I am not sure how valuable this would be, and I believe the insights we would be looking to gain would not be provided here.

https://github.com/USDA-FSA/fsa-design-system/graphs/traffic

**Recommendation:** Setup a GA account and implement it on both the Design System and FSA Style gh pages sites. Add DAP tracking code to all public facing websites, [as directed](https://www.whitehouse.gov/sites/whitehouse.gov/files/omb/memoranda/2017/m-17-06.pdf).

**Comment by francisrupert** [comment]
@bignamehere,

Can you additionally determine DAP, https://www.digitalgov.gov/services/dap/, implications? My general understanding, unless it's changed, is that it utilizes GA. Plus, since this is a public-facing gov site, it appears to be required.

**Comment by bignamehere** [comment]
@francisrupert yep, I am reading up on it, and yes it is required on all public pages. It looks like we need to create a Google account associated with our .gov email addresses and [apply for access](https://digital.gov/guides/dap/gaining-access-to-dap-data/). Still looking into what the benefits of DAP are over GA, or if they are the same things.

**Comment by bignamehere** [comment]
@francisrupert 

I reviewed the Memorandum for the DAP, and here are additional considerations for our public systems that we might need to address.

- Privacy Program Page (link to USDA policy?)
- U.S. Digital Registry at: http://www.digitalgov.gov/services/u-s-digital-registry/

lastly, it seems we should not be displaying the "An official website of the United States Government" on the GH Pages site, because it is not a .gov or .mil site.

Reference: https://www.whitehouse.gov/sites/whitehouse.gov/files/omb/memoranda/2017/m-17-06.pdf

**Comment by bignamehere** [comment]
@francisrupert Recommendation: Use Google Analytics tracking because it was quick and easy to implement. The GA learning curve is a bit steep, but once learned, finding data and analyzing User behavior can become easier.

**Comment by bignamehere** [comment]
implemented and closing
